const projects = [
  {
    name: "Dryly",
    img: "https://images.unsplash.com/photo-1560060141-7b9018741ced?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2341&q=80",
    slug: "dryly",
    overview: "",
    project_type: "Website + App + Backend",
    technologies: "React,React Native,APIs,Design,Databases,NodeJS,MongoDB",
    project_image: "",
    link: "https://www.dryly.in/",
  },
  {
    name: "BOLDbot",
    img: "https://images.unsplash.com/photo-1577563908411-5077b6dc7624?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Ym90fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    slug: "bold-bot",
    overview: "",
    project_type: "Website + Backend",
    technologies: "NextJS,Swift,APIs,Design,Databases",
    project_image: "",
    link: "https://www.boldbot.in/",
  },
  {
    name: "Rentupg",
    img: "https://images.unsplash.com/photo-1618347191821-51285853505f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    slug: "rentpug",
    overview: "",
    project_type: "Website + Backend",
    technologies: "NextJS,APIs,Design,Databases",
    project_image: "",
    link: "https://rentupg.vercel.app/",
  },
  {
    name: "Photography",
    img: "https://i.ibb.co/gyHkDR8/IMG-2195.jpg",
    slug: "photography",
    overview: "",
    project_type: "Website + Backend",
    technologies: "NextJS,APIs,Design,Databases",
    project_image: "",
    link: "https://jayeshphotography.vercel.app/",
  },
  {
    name: "Crypto Tracker",
    img: "https://images.unsplash.com/photo-1621504450181-5d356f61d307?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    slug: "crypto-tracker",
    overview:
      "The aim of Crypto Tracker was to create a responsive web-based platform that works hand in hand with its iOS counterpart to track cryptocurrency prices live, offering detailed analysis and intuitive portfolio management features. The web application was developed to provide users a comprehensive look into the fluctuating world of cryptocurrencies, making it simpler to monitor top movers, market stats, and individual coin details. Crafted with efficiency and performance in mind, the project leverages TypeScript for robust, error-free coding and React for an interactive UI, with Vite acting as the build tool. The app uses the CoinGecko API to provide real-time data updates, ensuring the currency prices are always current. The application architecture is built around the context API for effective state management, while user data like portfolio details are securely stored via localstorage. In terms of visual data representation, Chart.js was used to render dynamic and insightful charts. For seamless user experience, the app includes features such as the ability to search for specific coins and add them to one's portfolio. Routing was made possible using the React Router library, allowing for a multi-page feel in a single-page application.",
    project_type: "Website + App",
    technologies: "React,Swift,APIs,Design",
    project_image: "",
    link: "https://crypto-tracker-web.vercel.app/",
  },
  {
    name: "Leafy Lane",
    img: "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1771&q=80",
    slug: "leafy-lane",
    overview: "",
    project_type: "Website",
    technologies: "React,Design,Framer Motion",
    project_image: "",
    link: "https://leafy-lane.vercel.app/",
  },
];

export default projects;
